kind: pipeline
name: default
steps:
- name: build2
  image: maven:3.5.0-alpine
  commands:
    - mvn -B clean package 
- name: create-container
  image: plugins/docker
  settings:
    auth: oFzFuHEmJNQbFoBnoM37
    repo: registry.gitlab.com/vincenzofodera/testproject
    registry: registry.gitlab.com
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
- name: deploy
  image: quay.io/honestbee/drone-kubernetes:master
  settings:
    deployment: pod
    kubernetes_server: ${KUBERNETES_SERVER}
    # kubernetes_cert: ${KUBERNETES_CERT}
    kubernetes_token: ${KUBERNETES_TOKEN}
    repo: registry.hkoerber.de/blog
    container: blog
    tag: ${DRONE_COMMIT_SHA}
    namespace: default
    secrets:
      - KUBERNETES_SERVER
      # - KUBERNETES_CERT
      - KUBERNETES_TOKEN